import './globals.css';
import { ClerkProvider } from '@clerk/nextjs/app-beta';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className="min-h-screen flex flex-col items-center p-4 w-full">
          {/* <Sidebar /> */}
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
